### PR TITLE
Removed extra paranthesis and added prediction step to the test

### PR DESCRIPTION
**Pull request by kxk302**
### Pull Request Checklist

- [ X] Check python style, using `flake8 ./galaxy_ml`.
- [ X] Run API tests, using `cd galaxy_ml; nosetests ./tests -sv`.
- [ ] Check tool lint, using `cd galaxy_ml/tools; planemo lint`.
- [ ] Run tool tests, using `cd galaxy_ml/tools; planemo test`.
- [ ] Update `docs/CHANGELOG`, if applicable.
- [ ] Update `README.md`, if applicable.

@qiagu I removed an extra parenthesis. Also updated test to do prediction as well.

### CODE REVIEW

**Comment by qiagu** [comment]
@kxk302  Ha, I also found the error, and fixed it in another PR. Could you rebase this PR? Hope Travis tests will work soon. Thanks.

**Comment by kxk302** [comment]
> @kxk302 Ha, I also found the error, and fixed it in another PR. Could you rebase this PR? Hope Travis tests will work soon. Thanks.

@qiagu Pulled from upstream master and merged into my branch. So, the multi-output flag is True by default now, right?

**Comment by qiagu** [comment]
@kxk302  Great! To the best of my knowledge, a simple `True` should be fine for all cases I can imagine, at least it passes all tests.  Will revert it if we meet a counter case in the future.

**Comment by qiagu** [comment]
@kxk302  Thanks!

**Comment by kxk302** [comment]
Thank you @qiagu!

**Pull request merged**
